_prefs: 
  mapid: gnz.43969b30
  saveCenter: false
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -59.3545
  - 3.6619
  - 16
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: 
  - landcover
  - landuse
  - contour.line
  - hillshade
  - waterway
  - water
  - aeroway
  - barrier_line
  - building
  - landuse_overlay
  - tunnel
  - road
  - bridge
  - admin
  - country_label_line
  - country_label
  - marine_label
  - state_label
  - place_label
  - water_label
  - poi_label
  - road_label
  - waterway_label
  - housenum_label
  - contour.label
maxzoom: 22
minzoom: 0
name: Ethnocart
source: "mapbox:///mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v5"
styles: 
  - style.mss
  - road.mss
  - labels.mss
  - places.mss
  - contours.mss
  - landuse.mss
template: ''
